baseURL = "http://secdev.com/"
languageCode = "en-us"
title = "SecDev"
theme = "grayscale"
[Params]
    # Provide some metadata for search and indexing services
    description = "The SecDev Group provides services at the nexus of Security and Development. "
    author = "SecDev"
